In [1]:
from src.data import *
prices = download_prices()
prices, dropped = clean_prices(prices)
checks, suspicious = validate(prices)
print(checks)
print("dropped:", dropped)
suspicious

{'n_days': 2663, 'n_assets': 21, 'remaining_nans': 0, 'non_positive_prices': 0, 'daily_moves_over_20pct': 2}
dropped: []

Ticker,ASIANPAINT.NS,AXISBANK.NS,BHARTIARTL.NS,HDFCBANK.NS,HINDUNILVR.NS,ICICIBANK.NS,INFY.NS,ITC.NS,KOTAKBANK.NS,LT.NS,...,NESTLEIND.NS,NTPC.NS,RELIANCE.NS,SBIN.NS,SUNPHARMA.NS,TCS.NS,TITAN.NS,ULTRACEMCO.NS,WIPRO.NS,^NSEI
Date,,,,,,,,,,,,,,,,,,,,,
2017-10-25,-0.017336,0.046576,0.027288,-0.038562,0.001889,0.146877,0.009498,0.008427,-0.051750,0.053958,...,-0.011764,0.009359,0.006048,0.276872,-0.021139,-0.004472,-0.025245,0.055156,0.007075,0.008587
2020-03-23,-0.140279,-0.279108,-0.119529,-0.126069,-0.088707,-0.178479,-0.100393,-0.120798,-0.129996,-0.162658,...,-0.084893,-0.059692,-0.131539,-0.134620,-0.111568,-0.071073,-0.114875,-0.145222,-0.050502,-0.129805

In [6]:
from pathlib import Path

Path("data/processed").mkdir(parents=True, exist_ok=True)
Path("outputs/charts").mkdir(parents=True, exist_ok=True)

prices.to_parquet("data/processed/prices.parquet")

rets = prices.pct_change().dropna()
big_moves=rets[rets.abs() > 0.20].stack().dropna()
print(big_moves)

Date        Ticker
2017-10-25  SBIN.NS        0.276872
2020-03-23  AXISBANK.NS   -0.279108
dtype: float64

In [7]:
prices.loc["2020-03-16":"2020-03-25", ["AXISBANK.NS", "HDFCBANK.NS", "^NSEI"]]

Ticker      AXISBANK.NS  HDFCBANK.NS        ^NSEI
Date
2020-03-16   506.094910   465.649445  9197.400391
2020-03-17   485.944672   454.281891  8967.049805
2020-03-18   471.118073   408.532257  8468.799805
2020-03-19   426.140686   417.220978  8263.450195
2020-03-20   426.041168   411.304230  8745.450195
2020-03-23   307.129761   359.451538  7610.250000
2020-03-24   301.656860   357.657959  7801.049805
2020-03-25   325.190369   399.144745  8317.849609

In [8]:
import yfinance as yf
yf.download("AXISBANK.NS", start="2020-03-16", end="2020-03-26",
            auto_adjust=False, progress=False, threads=False)

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,AXISBANK.NS,AXISBANK.NS,AXISBANK.NS,AXISBANK.NS,AXISBANK.NS,AXISBANK.NS
Date,,,,,,
2020-03-16,506.094971,508.600006,545.000000,502.350006,542.349976,21542970
2020-03-17,485.944702,488.350006,531.299988,477.450012,515.150024,20590414
2020-03-18,471.118042,473.450012,506.049988,392.100006,490.000000,36240904
2020-03-19,426.140686,428.250000,464.950012,423.750000,441.049988,33243997
2020-03-20,426.041199,428.149994,449.700012,414.200012,431.399994,30764236
2020-03-23,307.129791,308.649994,392.000000,302.000000,385.350006,37622635
2020-03-24,301.656860,303.149994,337.500000,291.000000,331.950012,50681510
2020-03-25,325.190338,326.799988,363.750000,286.000000,293.500000,51993973